config/routes.rb
LindaApp::Application.routes.draw do
  root 'static_pages#home'

  controller :static_pages do
    get "links"
    get "contact"
    get "bio"
  end

  get 'work' => 'galleries#index'

  controller :sessions do
    get    'login'  => :new
    post   'login'  => :create
    delete 'logout' => :destroy
  end
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :images

  def to_param
    title.parameterize
  end

  private

  def source
    dropbox.find dropbox_path
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :gallery

  def to_param
    title.parameterize
  end

  def url
    @url ||= source.direct_url.url
  end

  def thumbnail
    @thumbnail ||= thumbnail_file.public_url.to_s
  end

  def thumbnail_file
    s3.objects["thumbs/#{title}.jpg"]
  end

  def thumbnail_source
    source.thumbnail size: 'l'
  end

  private

  def source
    dropbox.ls(dropbox_path).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  def index
    @galleries = Gallery.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_url if session[:logged_in]
  end

  def create
    if valid_login?
      session[:logged_in] = true
      redirect_to root_url
      flash[:success] = "Signed in!"
    else
      flash[:danger] = 'Wrong password'
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to root_url
    flash[:success] = "You're now logged out"
  end

  private

  def valid_login?
    params[:login][:username] == ENV['USERNAME'] &&
      params[:login][:password] == ENV['PASSWORD']
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def work
  end

  def links
  end

  def contact
  end

  def bio
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    session[:logged_in]
  end
end

app/views/galleries/index.html.erb
<% @galleries.each do |gallery| %>
  <div class="gallery" id="<%= gallery.to_param %>">
    <h1><%= gallery.title %></h1>
    <ul class="row">
      <% gallery.images.each do |image| %>
        <li><%= image_tag image.thumbnail %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

<footer>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default">
	<div class="navbar-header">
   <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
	    <span class="sr-only">Toggle navigation</span>
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	  </button>
		<%= link_to 'Linda Armstrong', root_url, class: 'navbar-brand' %>
	</div>

  <div class="collapse navbar-collapse" id="navbar-collapse">
  	<ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'Home', root_path %></li>
  		<li><%= link_to 'Work', work_path %></li>
  		<li><%= link_to 'Links',links_path %></li>
  		<li><%= link_to 'Bio', bio_path %></li>
  		<li><%= link_to 'Contact', contact_path %></li>
      <% if logged_in? %>
        <li><%= link_to 'Log out', logout_path, method: :delete %></li>
      <% end %>
  	</ul>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Linda Armstrong</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext',
  media: 'all' %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header'%>
<div class="container">
<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %> alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert">
			<span aria-hidden="true">&times;</span>
			<span class="sr-only">Close</span>
		</button>

		<%= value %>
	</div>
<% end %>
	<%= yield %>
</div>
<%= render 'layouts/footer'%>
</body>
</html>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<div class="row" id="galleries">
	<div class="col-md-8 clearfix">
		<div class="col-sm-6">
			<%= link_to work_path anchor: 'birds' do  %>
				<% image_tag('photo 1.jpg', class: 'img-responsive img-rounded') %>
			<% end %>
		</div>

		<div class="col-sm-6">
			<%= link_to work_path anchor: 'beach' do  %>
				<% image_tag 'beach.jpg', class: 'img-responsive img-rounded' %>
			<% end %>
		</div>

		<div class="col-sm-6">
			<%= link_to work_path anchor: 'collecting-excursions' do  %>
				<% image_tag '1.CollectingExcursions.jpg', class: 'img-responsive img-rounded' %>
			<% end %>
		</div>

		<div class="col-sm-6">
			<%= link_to work_path anchor: 'collecting-excursions' do  %>
				<% image_tag 'Agaric.jpg', class: 'img-responsive img-rounded' %>
			<% end %>
		</div>
	</div>

	<div class="col-md-4">
		<%= link_to work_path anchor: 'collecting-excursions' do  %>
			<% image_tag 'WooleyAdelgid.jpg', class: 'img-responsive img-rounded' %>
		<% end %>
	</div>
</div>

app/views/static_pages/links.html.erb
<h1>StaticPages#links</h1>
<p>Find me in app/views/static_pages/links.html.erb</p>